export const dynamic = "force-dynamic";
import { getUserProfileFromToken } from "@/app/actions/auth";
import { getChats } from "@/app/actions/chats";
import AsideMenu from "@/app/sensei/_components/AsideMenu";
import ChatBox from "@/app/sensei/_components/ChatBox";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AniSensei | Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUserProfileFromToken();
  const userEmail = user?.email;

  const chats = userEmail ? await getChats(userEmail) : [];

  return (
    <section className="h-auto flex lg:flex-row flex-col min-h-screen">
      <AsideMenu initialChats={chats} />
      {children}
    </section>
  );
}
