import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./_components/Header";
import { Navbar } from "./_components/Navbar";

export const metadata: Metadata = {
  title: "AniSensei | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <Header />
        <main>{children}</main>
        <Navbar />
      </body>
    </html>
  );
}
