import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/app/_context/AuthContext";

export const metadata: Metadata = {
  title: "AniSensei | Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <AuthProvider>
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
