import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AniSensei | Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <main>{children}</main>
      </body>
    </html>
  );
}
